version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_db
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"